name: Update Filter Lists

on:
  schedule:
    - cron: '0 0 */2 * *' # Runs every 2 days at midnight
  push:
    branches:
      - main

jobs:
  update-filter-lists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Combine filter lists
        run: |
          python scripts/auto_combine.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add nsfw/nsfw_combined.txt
          git commit -m 'Automatic DNS Filter Updates'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
